### PR TITLE
proto: implement Stringer interface on proto{syntax,label,type}

### PR DESCRIPTION
**Pull request by glerchundi**

### CODE REVIEW

**Comment by rodaine** [comment]
The prefixes on the labels and types are [canonical from their definitions](https://github.com/protocolbuffers/protobuf/blob/044c766/src/google/protobuf/descriptor.proto#L138-L176). We should not remove them from their string representation. The trimming should ideally happen in your tool, not PG*.

**Comment by rodaine** [comment]
I am OK with delegating through the `String` method from the underlying types however.

**Comment by glerchundi** [comment]
Addressed but this doesn't solve my problem at all. Will file a new issue with another proposal in this regard.

**Comment by rodaine** [comment]
Thanks! Sorry for the delay in merging.

**Pull request merged**
