### PR TITLE
Switch to go modules

### PR DESCRIPTION
**Pull request by rvolosatovs**
Switch to go modules to remove the `glide` dependency and simplify using of this library as a dependency.
Since the feature is opt-in in `go 1.11`, set `GO111MODULE=on` in `Makefile`
Merging this will break support for go versions pre-1.11
Refs #27 
Closes https://github.com/lyft/protoc-gen-star/issues/61

### CODE REVIEW

**Comment by rodaine** [comment]
Thanks for the patch! Adding the mod files is great but please leave the glide files in place for now, we still use it internally.

**Comment by rvolosatovs** [comment]
@rodaine any update on this?

**Comment by rvolosatovs** [comment]
@rodaine  :point_up:

**Comment by rvolosatovs** [comment]
Any chance this will be merged?

**Comment by tmc** [comment]
Refs https://github.com/lyft/protoc-gen-star/issues/61

**Comment by jasonwzm** [comment]
What is the current status of this PR?

**Comment by rvolosatovs** [comment]
I haven't updated it for a while.
In case there is a real intent to merge it, I can check that everything is in order and update if necessary.

**Comment by rodaine** [comment]
Apologies for the delay. Yes, we still want to do this. Internally, we're in the process of migrating codebases from glide -> modules, so we can't remove the glide manifests yet, but getting the modules in place as the last of 0.x and then cutting v1 with modules alone is the plan.

Let me know if you need anything from me. This week, I will be focusing on our open source tools and getting through the backlogs.

**Comment by rvolosatovs** [comment]
Upgraded to Go 1.13.
Successfully rebased on latest `master` without merge conflicts.
Should be good to go, but I did only basic testing of the rebased version.

**Comment by rvolosatovs** [comment]
@rodaine any update on this?

**Comment by wozz** [comment]
any updates on this?

**Comment by rodaine** [comment]
Closed by #81

**Pull request closed without merging**
