### PR TITLE
persister: add optional support

### LINKED ISSUE #75: [feature request] proto3 optional
any plan to support proto3 optional?

ref: 
[proto3 field presence](https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md)
[proto3 optional impl](https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md)

Need modify `persister.go`'s `Persist` method adding or reading ` --experimental_allow_proto3_optional` flag from command-line?:
```
resp.SupportedFeatures = proto.Uint64(uint64(plugin_go.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL))
```

### PR DESCRIPTION
**Pull request by glerchundi**
This changes adds the optional support to the code generation response.
It unconditionally adds this flag as the support should come in the
generator using this library.

Closes #75

### CODE REVIEW

**Comment by glerchundi** [comment]
@rodaine would you mind taking a look at this? Now that. protobuf 3.15 and as they made the optional response mandatory in case an `optional` keyword is present it would be good to merge this one and start propagating it to the rest of the community (`protoc-gen-validate` for example).

🙏 

I already tested in my environment by using the replace statement in `go.mod` and it works.

**Comment by akonradi** [comment]
@dkunitsk did you get a chance to review?

**Comment by dkunitsk** [comment]
> @dkunitsk did you get a chance to review?

Sorry for the delay. Will look into getting approver access today.

**Review by jcapote-lyft — APPROVED** [review]

**Comment by dkunitsk** [comment]
^ don't know what I was expecting.

**Comment by dkunitsk** [comment]
I filed the role request for read/write access to this repo on our end. Once that comes through will merge this in. Thanks Julio for the review.

**Comment by glerchundi** [comment]
Glad to see this progressing! Thanks @dkunitsk for pushing this forward 🥳

**Comment by glerchundi** [comment]
Ultra friendly ping @dkunitsk

**Comment by dkunitsk** [comment]
Well this is unlucky @glerchundi. Just as I got access to this repo (on Friday) a PGG change was released that broke tests. I am trying to get a patch out. I wish in the meantime I could merge manually but it looks like I can't bypass the github checks. I know we have stretched your patience tremendously - really sorry about this. cc @akonradi

**Comment by glerchundi** [comment]
Hi @dkunitsk, sorry for the looooong delay. Thanks for you time! Is there something I can do on my side to help you deal with these failures? If i'm not mistaken those seem unrelated to this change, right? (`protoc-gen-go: invalid Go import path "BAD.pack--age.name$" for "entities.proto"`)

Let me know if I can help, I'll happily do.

**Comment by sarthak40** [comment]
hi folks, how can I help progress this forward?

**Comment by akonradi** [comment]
@glerchundi yes, but we should still fix CI first. It looks like the problem is that [this package name](https://github.com/lyft/protoc-gen-star/blob/8bc36edf5b43c9b41d15646f1acb8a667aaf317d/lang/go/testdata/names/entities/entities.proto#L4) is supposed to be used to test that invalid characters get replaced, but even after the replacement it's falling afoul of the Go proto compiler. I believe that should be fairly easy to fix with the documentation link from the Go proto compiler in the failure log.

**Comment by sarthak40** [comment]
I'd really like to move this forward, mostly due to `[proto-gen-validate](url)`. From what I gather prefixing he packages with `./` should fix the issue.

Trying this locally after fixing that package, a bunch of others break as well. I am currently stuck at the error below though:
```
protoc-gen-go: no such flag -import_path
--go_out: protoc-gen-go: Plugin failed with status code 1.
make[1]: *** [Makefile:3: testdata-names] Error 1
```
...in the test package `lang/go/testdata/names/import_path`. Have you seen this before?

**Comment by sarthak40** [comment]
friendly ping @akonradi @glerchundi

**Comment by glerchundi** [comment]
> @glerchundi yes, but we should still fix CI first. It looks like the problem is that this package name is supposed to be used to test that invalid characters get replaced, but even after the replacement it's falling afoul of the Go proto compiler. I believe that should be fairly easy to fix with the documentation link from the Go proto compiler in the failure log.

#92 should fix the CI, the culprit seems to be aa non-versioned use of `protoc-gen-go`

**Comment by glerchundi** [comment]
I rebased this branch on top of #92 and another issue arised, and it was expected. The optional as well as SupportedFeatures flag isn't present in the pinned `protoc-gen-go@1.3.x` version.

The sane path to merge this change seems to be:
1. Although not required make the CI work again by merging #92
2. Change `protoc-gen-star` to make it compatible with latest versions of `golang/protobuf`. This would also simplify lots of tests that aren't needed anymore as unsupported use cases are blocked by the generator itself and therefore shouldn't be tested here.
3. Rebase this PR and finally...get it merged!

WDYT?

**Comment by akonradi** [comment]
That sounds like the right path forward, assuming that (2) includes bumping the pinned version of protoc-gen-go. I believe #86 might be useful.

**Comment by glerchundi** [comment]
> That sounds like the right path forward, assuming that (2) includes bumping the pinned version of protoc-gen-go.

Yeah, sure.

>  I believe #86 might be useful.

This would be the end game. Just double-checking that my proposal is to keep using `golang/protobuf` but the one that is a wrapper of `protocolbuffers/protobuf-go`. This would also make the transition a little bit easier as we would need to make some of the changes you included in #86 anyway.

If you don't mind I prefer to wait until @dkunitsk is pronounced :D

**Comment by dkunitsk** [comment]
@akonradi @glerchundi please see my thoughts in https://github.com/lyft/protoc-gen-star/pull/92#issuecomment-829758052

**Review by dkunitsk — APPROVED** [review]

**Comment by dkunitsk** [comment]
Thanks @glerchundi for the perseverance in getting through through.

**Comment by glerchundi** [comment]
It was a pleasure, thank you for pushing this forward as well. 👍

**Pull request merged**
